In [144]:
import numpy as np
import pandas as pd
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasClassifier
from keras.utils import np_utils
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.preprocessing import LabelEncoder
from sklearn.pipeline import Pipeline
from scipy import stats
from sklearn.linear_model import LogisticRegression as lr
from sklearn.metrics import accuracy_score

np.set_printoptions(threshold=np.inf)

In [145]:
# fix random seed for reproducibility
seed = 7
np.random.seed(seed)

In [146]:
# load dataset
df = pd.read_csv("train.csv", header=0)
xt=df.drop(["popularity"],axis=1)
yt=df["popularity"]
xte = pd.read_csv("test.csv", header=None)

In [147]:
# encode class values as integers
encoder = LabelEncoder()
encoder.fit(yt)
encoded_Y = encoder.transform(yt)
# convert integers to dummy variables (i.e. one hot encoded)
dummy_y = np_utils.to_categorical(encoded_Y)
print(dummy_y)

[[ 1.  0.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 1.  0.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]
 [ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 1.  0.  0

In [196]:
# define baseline model
# create model
model = Sequential()
model.add(Dense(600, input_dim=6, activation='relu'))
model.add(Dense(300, activation='relu'))
model.add(Dense(400, activation='relu'))
model.add(Dense(4, activation='softmax'))
# Compile model
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [197]:
model.fit(xt, dummy_y, epochs=200, batch_size=10)
scores = model.evaluate(xt, dummy_y)
print("\n%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))

Epoch 1/200
1628/1628 [==============================] - 2s 1ms/step - loss: 0.4792 - acc: 0.8059
Epoch 2/200
1628/1628 [==============================] - 1s 397us/step - loss: 0.2653 - acc: 0.8950
Epoch 3/200
1628/1628 [==============================] - 1s 393us/step - loss: 0.2211 - acc: 0.9134
Epoch 4/200
1628/1628 [==============================] - 1s 392us/step - loss: 0.1955 - acc: 0.9140
Epoch 5/200
1628/1628 [==============================] - 1s 400us/step - loss: 0.2047 - acc: 0.9097
Epoch 6/200
1628/1628 [==============================] - 1s 400us/step - loss: 0.1878 - acc: 0.9238
Epoch 7/200
1628/1628 [==============================] - 1s 400us/step - loss: 0.1759 - acc: 0.9195
Epoch 8/200
1628/1628 [==============================] - 1s 524us/step - loss: 0.1758 - acc: 0.9220
Epoch 9/200
1628/1628 [==============================] - 1s 411us/step - loss: 0.1549 - acc: 0.9330
Epoch 10/200
1628/1628 [==============================] - 1s 436us/step - loss: 0.1799 - acc: 0.9263
E

1628/1628 [==============================] - 1s 390us/step - loss: 0.0217 - acc: 0.9908
Epoch 83/200
1628/1628 [==============================] - 1s 385us/step - loss: 0.0130 - acc: 0.9963
Epoch 84/200
1628/1628 [==============================] - 1s 387us/step - loss: 0.0488 - acc: 0.9846
Epoch 85/200
1628/1628 [==============================] - 1s 388us/step - loss: 0.0102 - acc: 0.9963
Epoch 86/200
1628/1628 [==============================] - 1s 388us/step - loss: 0.0045 - acc: 0.9988
Epoch 87/200
1628/1628 [==============================] - 1s 419us/step - loss: 0.0077 - acc: 0.9982
Epoch 88/200
1628/1628 [==============================] - 1s 409us/step - loss: 0.0253 - acc: 0.9908
Epoch 89/200
1628/1628 [==============================] - 1s 402us/step - loss: 0.0840 - acc: 0.9785
Epoch 90/200
1628/1628 [==============================] - 1s 389us/step - loss: 0.0050 - acc: 0.9994
Epoch 91/200
1628/1628 [==============================] - 1s 391us/step - loss: 0.0025 - acc: 1.0000
Epo

Epoch 160/200
1628/1628 [==============================] - 1s 413us/step - loss: 5.6566e-07 - acc: 1.0000
Epoch 161/200
1628/1628 [==============================] - 1s 411us/step - loss: 5.2780e-07 - acc: 1.0000
Epoch 162/200
1628/1628 [==============================] - 1s 391us/step - loss: 4.6805e-07 - acc: 1.0000
Epoch 163/200
1628/1628 [==============================] - 1s 387us/step - loss: 4.5645e-07 - acc: 1.0000
Epoch 164/200
1628/1628 [==============================] - 1s 390us/step - loss: 4.1306e-07 - acc: 1.0000
Epoch 165/200
1628/1628 [==============================] - 1s 389us/step - loss: 3.7626e-07 - acc: 1.0000
Epoch 166/200
1628/1628 [==============================] - 1s 394us/step - loss: 3.6147e-07 - acc: 1.0000
Epoch 167/200
1628/1628 [==============================] - 1s 390us/step - loss: 3.4038e-07 - acc: 1.0000
Epoch 168/200
1628/1628 [==============================] - 1s 389us/step - loss: 3.1325e-07 - acc: 1.0000
Epoch 169/200
1628/1628 [=====================

In [199]:
predictions = model.predict(xte)
fc=predictions.argmax(axis=-1)+1
fc

array([1, 3, 1, 1, 2, 1, 4, 3, 4, 1, 3, 3, 4, 3, 1, 3, 1, 3, 1, 2, 3, 3, 3,
       4, 2, 3, 3, 4, 2, 3, 2, 1, 3, 4, 4, 1, 3, 3, 1, 4, 4, 1, 3, 2, 3, 1,
       2, 2, 3, 1, 1, 2, 2, 1, 4, 4, 2, 1, 4, 2, 4, 2, 3, 3, 4, 2, 4, 1, 1,
       2, 4, 4, 2, 1, 2, 1, 1, 4, 2, 3, 2, 4, 3, 3, 4, 3, 4, 2, 4, 2, 1, 2,
       2, 2, 4, 1, 2, 4, 4, 1], dtype=int64)

In [200]:
np.savetxt("ans.csv",fc,fmt="%d")